window_properties = [
  {
    "property_id": "73623763",
    "listing_price": 600000,
    "beds": 3,
    "baths": 1,
    "address": "Inverness Road, Worcester Park KT4",
    "latitude": 51.381693,
    "longitude": -0.223829,
    "detail_url": "https://www.zoopla.co.uk/for-sale/details/73623763/",
    "uprn": "5870015795",
    "property_name": "3 bed detached house for sale",
    "description": "Presenting this attractive three-bedroom detached house, ideally situated in a sought-after residential area within close proximity to Cheam Park Schools (making it an excellent choice for families). The property offers a welcoming and spacious layout, beginning with a generous entrance hall that leads to two versatile reception rooms. These bright and airy living spaces provide flexibility for both formal entertaining and relaxed family time. The separate fully fitted kitchen is thoughtfully designed with modern appliances and ample storage, creating an ideal environment for cooking and every-day living. A convenient downstairs WC adds to the practicality of the ground floor layout. Upstairs, three well-proportioned bedrooms offer comfortable accommodation, each with space for bedroom furniture and storage solutions. The modern family bathroom is finished to a high standard, featuring contemporary fixtures and fittings for a stylish and functional space. Additional benefits include a private driveway with parking for two cars (a valuable feature in this area). The property is presented in excellent decorative order throughout, with neutral tones and quality finishes that will appeal to a wide range of buyers. Located within easy reach of local amenities, reputable schools, and transport links, this home combines convenience with comfort. This is a rare opportunity to secure a detached family home in a desirable location, offering both practicality and style for modern living. Early viewing is highly recommended to appreciate the full appeal of this superb property. EPC Rating: D Location Discover Worcester Park â A Commuter Favourite with a Village Feel Worcester Park is a popular and well-connected suburban area on the SurreyâSouth West London border, offering a perfect mix of convenience, community, and green space. Just 10 miles from central London, the area is ideal for commuters, with Worcester Park Station providing direct trains to London Waterloo in under 30 minutes. Easy access to the A3 and M25 makes it equally convenient for drivers. The high street offers a great selection of independent shops, cafÃ©s, supermarkets, and restaurants, while nearby Kingston, New Malden, and Epsom offer additional shopping and leisure options. Families enjoy the local parks, including Manor Park, Cuddington Recreation Ground, and Green Lane Park, perfect for children, sports, and dog walking. Worcester Park is especially popular with families due to its excellent local schools, including Cuddington Community Primary, Cheam Common Infants and Juniors, and Malden Parochial. The housing stock is diverse, with a mix of 1930s semi-detached homes, Victorian cottages, modern developments, and family-friendly streets. The Hamptons, a sought-after modern development with its own gym and parkland, offers a unique lifestyle within the area. With a strong community feel, frequent local events, and access to both urban and rural surroundings, Worcester Park continues to attract buyers and renters looking for a peaceful, well-connected place to call home. Parking - Driveway Driveway space for two cars Disclaimer Kaybridge Residential is a trading name of kbr Group Ltd. Registered in England &amp; Wales, Company No: 16532664. Registered Office: 23 Stoneleigh Broadway, Epsom, KT17 2JE. Every care has been taken in the preparation of property particulars, but we do not guarantee the accuracy of the information provided. The details are intended as a general guide and do not constitute, nor form part of, an offer or contract. All measurements, floor areas, distances, and descriptions are approximate and should not be relied upon as statements of fact. Prospective purchasers/tenants must satisfy themselves by inspection or otherwise as to the correctness of each statement contained in these particulars. Fixtures, fittings, and appliances referred to have not been tested, and no guarantee can be given that they are in working order. Kaybridge Residential, its employees, or representatives have no authority to make or give any representation or warranty whatsoever in relation to a property",
    "features": "Detached House, Three Bedrooms, Downstairs WC, Driveway Space For Two Cars, Modern Bathroom, Fully Fitted Kitchen, Close Proximity to Cheam Park Schools",
    "tenure": "",
    "floor_size": "958",
    "listing_update_date": "2026-07-03",
    "postcode": "KT4 8PT",
    "chain_free": null,
    "epc_rating": "D",
    "council_tax_band": "E",
    "estimate_price": 597000,
    "estimate_low": 567000,
    "estimate_high": 627000,
    "estimate_url": "https://www.zoopla.co.uk/property/uprn/5870015795/",
    "garden_facing": "Unknown",
    "dev_types": "None",
    "dev_planning": "None",
    "dev_unmodernized": false,
    "parking_type": "Driveway",
    "parking_spaces": 2,
    "parking_ev": false,
    "outdoor_space": "None",
    "period_features": true,
    "double_glazing": true,
    "quiet_rating": "Private Road",
    "river_proximity": "None",
    "price_delta": 3000,
    "school_commute_seconds": 3343,
    "school_commute_text": "56 mins",
    "school_distance_km": 9.94,
    "school_commute_url": "https://www.google.com/maps/dir/?api=1&travelmode=transit&origin=51.381693,-0.223829&destination=51.41188,-0.29607",
    "office_commute_seconds": 4273,
    "office_commute_text": "1 hour 11 mins",
    "office_distance_km": 21.36,
    "office_commute_url": "https://www.google.com/maps/dir/?api=1&travelmode=transit&origin=51.381693,-0.223829&destination=51.52281,-0.09015"
  },
  {
    "property_id": "73619865",
    "listing_price": 1000000,
    "beds": 4,
    "baths": 3,
    "address": "102 Summer Road, Thames Ditton KT7",
    "latitude": 51.394882,
    "longitude": -0.336036,
    "detail_url": "https://www.zoopla.co.uk/for-sale/details/73619865/",
    "uprn": "100061324526",
    "property_name": "4 bed detached house for sale",
    "description": "Ref: TK1239 // Discover this immaculate four-bedroom, three-bathroom detached family home, ideally situated on a sought-after tree-lined road in a high-demand location, offered with no onward chain and is exchange ready. This beautifully presented residence features two spacious reception rooms, providing versatile living spaces perfect for relaxation and entertaining. The interior is meticulously maintained, ensuring a turnkey experience for its new occupants. Outside, the property benefits from a private driveway offering convenient parking for two cars. To the rear, a large garden awaits, providing ample outside space for leisure and enjoyment. Located in KT7 0QP, this home offers the added benefit of being within walking distance to the riverside, perfect for scenic strolls and outdoor activities. An early viewing is highly recommended to fully appreciate the quality and lifestyle on offer. Please enquire for a slot at our Open Day on the 11th of July. Disclaimer: Ai has been used to stage the property.",
    "features": "Ref: TK1239, No Chain, Open Day 11th of July, Exchange Ready, Guide Price Â£1,000,000 - Â£1,050,000, High Demand Location, Enquire for a Slot, Walking distance to Riverside, Tree Lined Road, Driveway for two cars &amp; Garage",
    "tenure": NaN,
    "floor_size": "1270 sqft",
    "listing_update_date": "2026-07-03",
    "postcode": "KT7 0QP",
    "chain_free": "True",
    "epc_rating": "E",
    "council_tax_band": "E",
    "estimate_price": 1090000,
    "estimate_low": 1040000,
    "estimate_high": 1140000,
    "estimate_url": "https://www.zoopla.co.uk/property/uprn/100061324526/",
    "garden_facing": "Unknown",
    "dev_types": NaN,
    "dev_planning": NaN,
    "dev_unmodernized": "False",
    "parking_type": NaN,
    "parking_spaces": 2,
    "parking_ev": "False",
    "outdoor_space": "Large Garden",
    "period_features": "False",
    "double_glazing": "True",
    "quiet_rating": "Private Road",
    "river_proximity": "Walking distance to the river",
    "price_delta": -90000,
    "school_commute_seconds": 1790,
    "school_commute_text": "30 mins",
    "school_distance_km": 5.37,
    "school_commute_url": "https://www.google.com/maps/dir/?api=1&travelmode=transit&origin=51.394882,-0.336036&destination=51.41188,-0.29607",
    "office_commute_seconds": 5117,
    "office_commute_text": "1 hour 25 mins",
    "office_distance_km": 30.04,
    "office_commute_url": "https://www.google.com/maps/dir/?api=1&travelmode=transit&origin=51.394882,-0.336036&destination=51.52281,-0.09015"
  },
  {
    "property_id": "73619853",
    "listing_price": 600000,
    "beds": 3,
    "baths": 1,
    "address": "26 Burnham Road, Morden SM4",
    "latitude": 51.397194,
    "longitude": -0.193072,
    "detail_url": "https://www.zoopla.co.uk/for-sale/details/73619853/",
    "uprn": "48009654",
    "property_name": "3 bed end terrace house for sale",
    "description": "Location, location, location........This seldom available three bedroom end of terrace, extended home is located within the much sought after 'A and B' roads which are renowned for the convenience they provide due to their close proximity to Morden underground station and Morden town centre. With its wealth of amenities as well as the nearby Morden South train station and many local bus routes connecting neighbouring town centres such as Wimbledon, Colliers Wood and Raynes Park adding to the numerous transport options providing an optimum commute to and from Central London, making this an ideal purchase for commuters, buy to let investors and first time buyers alike. Providing the rarely found blend of convenience and tranquillity are the vast recreational spaces of the nearby National Trust's Morden Hall Park, Ravensbury Park and Morden Park to name but a few, a balance rarely able to be purchased when in such close proximity to a thriving town centre. The bright, airy, flexible accommodation comprises of a lounge, a kitchen and a shower room to the ground floor and three bedrooms to the first floor. Externally the property benefits from private front, side and rear gardens, the front of which provides off street parking for 4 cars and the rear is considerably larger than average when compared to many of the similar properties within the neighbouring popular roads. In addition to itâs original construction in the 1930âs, an extension to the rear was constructed in more recent times. Currently the extension operates as a self contained 207sg ft/19.27sq m annex with itâs own private access, providing both the opportunity to rent out and financially contribute to monthly expenditure or to provide a perfect solution to those seeking a property to provide accommodation for an elderly relative with restricted mobility or multigenerational households. Equally the positioning of the extension lends itself to providing the highly desired seamless open plan kitchen/diner which leads directly to the private rear garden. Naturally this would be subject to some alterations and the relevant consent. It is highly recommended that you arrange to view without delay to fully appreciate the many benefits and attributes as well as ensuring that you avoid missing out on this fantastic opportunity. Important note to potential purchasers &amp; tenants: We endeavour to make our particulars accurate and reliable, however, they do not constitute or form part of an offer or any contract and none is to be relied upon as statements of representation or fact. The services, systems and appliances listed in this specification have not been tested by us and no guarantee as to their operating ability or efficiency is given. All photographs and measurements have been taken as a guide only and are not precise. Floor plans where included are not to scale and accuracy is not guaranteed. If you require clarification or further information on any points, please contact us, especially if you are travelling some distance to view. Potential purchasers: Fixtures and fittings other than those mentioned are to be agreed with the seller. Potential tenants: All properties are available for a minimum of six months, with the exception of short term accommodation. A security deposit of at least one monthâs rent is required. Rent is to be paid one month in advance. It is the tenantâs responsibility to insure any personal possessions. Buyers information To conform with government Money Laundering Regulations 2019, we are required to confirm the identity of all prospective buyers. We use the services of our appointed compliance provider, Simplify, who will contact you directly at an agreed time to do this. They will need the full name, date of birth and current address of all buyers. There is a charge of Â£99 including VAT for this (for the transaction not per person), payable direct to Simplify. Referral fees We may refer you to recommended providers of ancillary services such as Conveyancing, Financial Services, Insurance and Surveying. We may receive a commission payment fee or other benefit (known as a referral fee) for recommending their services. You are not under any obligation to use the services of the recommended provider. The ancillary service provider may be an associated company of Goodfellows. GMO250119/",
    "features": NaN,
    "tenure": NaN,
    "floor_size": "1399 sqft",
    "listing_update_date": "2026-07-03",
    "postcode": "SM4 5LX",
    "chain_free": NaN,
    "epc_rating": "C",
    "council_tax_band": "C",
    "estimate_price": 596000,
    "estimate_low": 566000,
    "estimate_high": 626000,
    "estimate_url": "https://www.zoopla.co.uk/property/uprn/48009654/",
    "garden_facing": "Unknown",
    "dev_types": "Rear",
    "dev_planning": "Potential",
    "dev_unmodernized": "False",
    "parking_type": "Driveway",
    "parking_spaces": 4,
    "parking_ev": "False",
    "outdoor_space": "Small Garden",
    "period_features": "True",
    "double_glazing": "True",
    "quiet_rating": "Private Road",
    "river_proximity": NaN,
    "price_delta": 4000,
    "school_commute_seconds": 3444,
    "school_commute_text": "57 mins",
    "school_distance_km": 12.72,
    "school_commute_url": "https://www.google.com/maps/dir/?api=1&travelmode=transit&origin=51.397194,-0.193072&destination=51.41188,-0.29607",
    "office_commute_seconds": 3166,
    "office_commute_text": "53 mins",
    "office_distance_km": 17.35,
    "office_commute_url": "https://www.google.com/maps/dir/?api=1&travelmode=transit&origin=51.397194,-0.193072&destination=51.52281,-0.09015"
  },
  {
    "property_id": "73618883",
    "listing_price": 850000,
    "beds": 3,
    "baths": 1,
    "address": "5 Watermans Close, Kingston Upon Thames KT2",
    "latitude": 51.418544,
    "longitude": -0.303887,
    "detail_url": "https://www.zoopla.co.uk/for-sale/details/73618883/",
    "uprn": "100021764323",
    "property_name": "3 bed semi-detached house for sale",
    "description": "This charming four bedroom semi-detached house offers a delightful blend of comfort and potential, situated within this incredible riverside location. This spacious property measures 1421sqft arranged over three floors. The ground floor consists of a generous living room with bay window, downstairs WC, utility room and and a kitchen to the rear overlooking the garden. The first floor provides two excellent double bedrooms with the front bedroom including a superb terrace, a real rarity for the area. The second floor contains another double bedrooms, family bathroom, separate WC and a fourth bedroom currently used as a walk in wardrobe, which could also be utilised as a home office. Externally there is a private Southerly aspect rear garden with excellent storage sheds. There is also side access into the garden. Additionally, there is off street parking for two cars at the front, a real bonus in this sought after location. This property presents tremendous scope for further development, subject to necessary planning consents, making it an exciting opportunity for those looking to personalise and design their dream home. In summary, this semi-detached house in Kingston upon Thames is a rare find, combining a prime location, ample living space, and the potential for further enhancements. Do not miss the chance to make this wonderful property your own. Sold with no onward chain. Waterman's close is a small development of town houses off Lower Ham Road which is one of the extremely sought after North Kingston River Roads. Conveniently positioned for Kingston town centre, station and Richmond Park, the property is positioned opposite Canbury Gardens and the River Thames. The standard of schooling in the immediate area is excellent for both private and state sectors and the area has an extensive range of leisure facilities including golf courses, tennis clubs, sailing, riding schools and private &amp; public health clubs",
    "features": "Sold with No Onward Chain!, Four Bedroom Semi Detached House, Generous Accommodation Approaching 1500sqft, Off Street Parking for Two Cars, Southerly Aspect Rear Garden, Potential for Development (stnc), Incredible Riverside Location, Opposite Canbury Gardens, Slow to Train Station &amp; Town Centre, EPC Rating - C",
    "tenure": NaN,
    "floor_size": "1421",
    "listing_update_date": "2026-07-03",
    "postcode": "KT2 5AS",
    "chain_free": "True",
    "epc_rating": "C",
    "council_tax_band": "Not available",
    "estimate_price": 1340000,
    "estimate_low": 1070000,
    "estimate_high": 1610000,
    "estimate_url": "https://www.zoopla.co.uk/property/uprn/100021764323/",
    "garden_facing": "South",
    "dev_types": "Rear",
    "dev_planning": "Potential",
    "dev_unmodernized": "False",
    "parking_type": "Driveway",
    "parking_spaces": 2,
    "parking_ev": "False",
    "outdoor_space": "Large Garden",
    "period_features": "True",
    "double_glazing": "True",
    "quiet_rating": "Private Road",
    "river_proximity": "River Thames",
    "price_delta": -490000,
    "school_commute_seconds": 620,
    "school_commute_text": "10 mins",
    "school_distance_km": 1.3,
    "school_commute_url": "https://www.google.com/maps/dir/?api=1&travelmode=transit&origin=51.418544,-0.303887&destination=51.41188,-0.29607",
    "office_commute_seconds": 4758,
    "office_commute_text": "1 hour 19 mins",
    "office_distance_km": 26.89,
    "office_commute_url": "https://www.google.com/maps/dir/?api=1&travelmode=transit&origin=51.418544,-0.303887&destination=51.52281,-0.09015"
  },
  {
    "property_id": "73618326",
    "listing_price": 1500000,
    "beds": 5,
    "baths": 3,
    "address": "14 Burnell Avenue, Richmond, United Kingdom TW10",
    "latitude": 51.430062,
    "longitude": -0.314981,
    "detail_url": "https://www.zoopla.co.uk/for-sale/details/73618326/",
    "uprn": "100022304134",
    "property_name": "5 bed terraced house for sale",
    "description": "A picturesque five bedroom house with river views. Description Behind its attractive faÃ§ade and picturesque landscaped frontage, this beautifully presented family home offers a wonderful balance of character, comfort and modern living. The heart of the home is the exceptional open-plan kitchen and dining space, flooded with natural light from a large roof lantern and glass sun room. Featuring bespoke cabinetry, a central island and generous entertaining areas, it provides the perfect setting for everyday family life as well as hosting guests. Sliding doors seamlessly connect the interior to the private rear garden, creating an effortless indoor-outdoor lifestyle. Throughout the property, the interiors have been thoughtfully designed with a calming palette, quality finishes and an abundance of natural light. Well-proportioned accommodation includes spacious reception areas, stylish bedrooms and contemporary family bathrooms, all presented to an impeccable standard. A particular highlight is the detached garden annex, discreetly positioned away from the main residence to provide complete privacy and independence. Ideal for visiting family and guests, the annex offers versatile additional accommodation and could also serve as a home office or studio. Outside, the charming front garden creates a welcoming first impression, with mature planting, lavender borders and a picket fence enhancing the home's kerb appeal. The rear garden provides a peaceful and secluded setting for relaxing, entertaining and family enjoyment. A superb home combining timeless character with modern convenience, ideally suited to families seeking generous living space in a highly desirable setting. Square Footage: 2,186 sq f",
    "features": "River View, Annexe, Large Front and Back Gardens, Picturesque Location, Balcony, Easy Parking, EPC Rating = C",
    "tenure": NaN,
    "floor_size": "2186",
    "listing_update_date": "2026-07-03",
    "postcode": "TW10 7YE",
    "chain_free": NaN,
    "epc_rating": "C",
    "council_tax_band": "E",
    "estimate_price": 1260000,
    "estimate_low": 1130000,
    "estimate_high": 1380000,
    "estimate_url": "https://www.zoopla.co.uk/property/uprn/100022304134/",
    "garden_facing": "Unknown",
    "dev_types": NaN,
    "dev_planning": NaN,
    "dev_unmodernized": "False",
    "parking_type": NaN,
    "parking_spaces": 0,
    "parking_ev": "False",
    "outdoor_space": NaN,
    "period_features": "True",
    "double_glazing": "True",
    "quiet_rating": "Unknown",
    "river_proximity": "River View",
    "price_delta": 240000,
    "school_commute_seconds": 1424,
    "school_commute_text": "24 mins",
    "school_distance_km": 3.19,
    "school_commute_url": "https://www.google.com/maps/dir/?api=1&travelmode=transit&origin=51.430062,-0.314981&destination=51.41188,-0.29607",
    "office_commute_seconds": 6091,
    "office_commute_text": "1 hour 42 mins",
    "office_distance_km": 25.21,
    "office_commute_url": "https://www.google.com/maps/dir/?api=1&travelmode=transit&origin=51.430062,-0.314981&destination=51.52281,-0.09015"
  },
  {
    "property_id": "73617732",
    "listing_price": 635000,
    "beds": 3,
    "baths": 2,
    "address": "5 Burford Road, Worcester Park KT4",
    "latitude": 51.385861,
    "longitude": -0.246744,
    "detail_url": "https://www.zoopla.co.uk/for-sale/details/73617732/",
    "uprn": "100021802216",
    "property_name": "3 bed semi-detached bungalow for sale",
    "description": "Connor Prince are pleased to offer this spacious and beautifully presented three bedroom semi-detached chalet bungalow with a 25'1 X 10'11 lounge/dining room, fitted kitchen with built in appliances, downstairs shower room and upstairs master bedroom with open plan en-suite bathroom. Situated in a cul-de-sac location close to local shops, bus stops, the A3 roadway and Worcester Park's mainline station giving access to Waterloo in 30 minutes. Entrance hallway Tiled flooring, built in cloaks and storage cupboards, double radiator. Lounge/dining room 25'1 X 10'11 Two double radiators, effect fireplace, double glazed doors onto rear garden, square arch through to:- fitted kitchen 9'5 X 7'5 Fitted with a range of high and low level cupboards and drawers, working top surfaces, inset single drainer stainless steel sink unit with mixer tap, double glazed window above, fitted fridge, freezer, washing machine, microwave and gas cooker with extractor fan above, tiled flooring. Bedroom two 14'8 X 10'11 Into angled bay double glazed window, double radiator, wall to wall fitted wardrobes providing hanging and shelved storage space. Bedroom three 9'5 X 8'8 Double glazed windows, double radiator. Shower room Comprising double length shower cubicle, vanity wash hand basin, low level w.c., fully tiled walls, towel rail/radiator, tiled flooring. Inner lobby and stairs up to:- master bedroom 15'1 X 13'5 Sloping ceilings with skylight windows, eaves storage cupboards, double radiator, wood flooring, open plan to:- Ensuite bathroom Comprising feature rolltop bath with mixer tap shower attachment, low level w.c. With wash hand basin, double radiator. Outside rear garden Extending to 45ft with artificial grass, raised flower bed, paved patio area, raised fishpond with filtration system, side access leading to:- detached garage 17'3 X 10'3 Personal door to rear garden, electric shutter doors, approached via an in and out cobbled carriage driveway providing off street parking for several cars. Front garden Artificial grassed area, feature lamppost. Council tax Band",
    "features": "Entrance hallway, 25'1 X 10'11 lounge/dining room, Fitted kitchen with built in appliances, Master bedroom with en-suite bathroom, Downstairs shower room, Double glazing and gas central heating, Detached garage, In and out driveway, Sole agents",
    "tenure": NaN,
    "floor_size": "979 sqft",
    "listing_update_date": "2026-07-03",
    "postcode": "KT4 7SU",
    "chain_free": NaN,
    "epc_rating": "C",
    "council_tax_band": "E",
    "estimate_price": 654000,
    "estimate_low": 621000,
    "estimate_high": 686000,
    "estimate_url": "https://www.zoopla.co.uk/property/uprn/100021802216/",
    "garden_facing": "South",
    "dev_types": NaN,
    "dev_planning": NaN,
    "dev_unmodernized": "False",
    "parking_type": "Driveway",
    "parking_spaces": 4,
    "parking_ev": "False",
    "outdoor_space": "Large Garden",
    "period_features": "True",
    "double_glazing": "True",
    "quiet_rating": "Cul-de-sac",
    "river_proximity": NaN,
    "price_delta": -19000,
    "school_commute_seconds": 2174,
    "school_commute_text": "36 mins",
    "school_distance_km": 7.2,
    "school_commute_url": "https://www.google.com/maps/dir/?api=1&travelmode=transit&origin=51.385861,-0.246744&destination=51.41188,-0.29607",
    "office_commute_seconds": 5327,
    "office_commute_text": "1 hour 29 mins",
    "office_distance_km": 22.82,
    "office_commute_url": "https://www.google.com/maps/dir/?api=1&travelmode=transit&origin=51.385861,-0.246744&destination=51.52281,-0.09015"
  }
];
